### ISSUE TITLE
Add DAP and USA.gov GA snippets

### ISSUE THREAD

**Issue by cew821** [GSA/analytics.usa.gov#11]
DAP-ception

**Comment by konklone** [comment]
We're hosting a copy of DAP 1.0 at https://dap.18f.us/dap-1.0.min.js. It's the same bucket as the data, so whatever URL we use for the analytics data snapshots (see #8) will apply for that as well. We're trying to use that for as many 18F projects as we can, and to offer it to as many DAP clients as want to use it, so that the DAP can be upgraded in one place.

**Comment by konklone** [comment]
Also, not sure if we want the site to report into usa.gov's individual existing and separate Google Analytics profile.

**Comment by konklone** [comment]
Realizing @tdlowden isn't on this repo as a watcher yet, so CCing him specifically. @tdlowden, you may want to Watch this repo, as we're ramping up work fast.

**Comment by konklone** [comment]
(Just added @tdlowden to the 18F team, at least temporarily, so he is now a Watcher.)

**Comment by gbinal** [comment]
> (Just added @tdlowden to the 18F team, at least temporarily, so he is now a Watcher.)

Added the DAP team in the GSA org, as well.  

> Also, not sure if we want the site to report into usa.gov's individual existing and separate Google Analytics profile.

I think it makes sense to fold up into the USA.gov profile.

**Comment by konklone** [comment]
> I think it makes sense to fold up into the USA.gov profile.

OK, I renamed the ticket to make it clear this needs both.

**Comment by tdlowden** [comment]
If I understand this, you mean make sure we have the DAP script on the page so that DAP can track the DAP dash traffic, yes? As far as I understand, all of the usa.gov pages in the CMS do this automatically, with both DAP and the USA.gov GA script tags. If we are going to do the subdomain thing, then we might have to add it ourselves, but that is easy enough.

**Comment by konklone** [comment]
@gbinal or @tdlowden, can one of you make sure this gets added to the project?

**Comment by tdlowden** [comment]
@konklone as soon as we get on the final location we can do this

**Comment by tdlowden** [comment]
@konklone here's the tag  <script language="javascript" id="_fed_an_ua_tag" src="http://www.usa.gov/resources/js/Universal-Federated-Analytics.1.0.js?agency=GSA&dclink=true"></script>

**Comment by gbinal** [comment]
rock.  @konklone - I'm happy to add but which branch should I offer a PR to?

**Comment by tdlowden** [comment]
as for usa.gov GA... let's circle back with Russell for this later

**Comment by konklone** [comment]
Closing in favor of #81.
