### ISSUE TITLE
Is "federal" needed in the real-time language

### ISSUE THREAD

**Issue by tdlowden** [GSA/analytics.usa.gov#119]
Someone who saw the screenshot we provided OMB has commented that the word federal doesn't appear anywhere. Since we only track federal websites, this could be significant point of confusion for state and local. Would the word "federal" fit in to make "people on federal government websites now"?

**Comment by leahbannon** [comment]
That's not quite right; it's in the about section several times. I agree that it'd be nice if it were clearer at the top of the page, but it definitely won't fit in the "people on" section. Open to other suggestions.

It's addressed a few times in the About this Site section: "This data provides a window into how people are interacting with the government online. The data comes from a unified Google Analytics account for U.S. federal government agencies known as the Digital Analytics Program." and "Not every government website is represented in this data. Currently, the Digital Analytics Program collects web traffic from almost 300 executive branch government domains out of about 1,350 domains total. This data is not a representative sample of all web traffic to government domains."

**Comment by tdlowden** [comment]
Apologies for the confusion; careless phrasing on my part. The person who gave feedback was specifically talking about the "people on" section. 

Point taken about fitting it in with current wording. Just to throw another idea out there, would it be more confusing to replace "government" with "federal"? 

People on federal websites now
People on government websites now

**Comment by leahbannon** [comment]
I think that's much less user friendly. What if we thought of it from a different frame? Like putting an asterisk? (Something like that, but not that!) cc @cew821 @kategarklavs

**Comment by tdlowden** [comment]
what about also linking the words "on government sites now" to https://analytics.usa.gov/demo/#explanation ?

**Comment by konklone** [comment]
So far it doesn't sound like we've found something we're all excited about. Here's what inserting "federal" looks like:

![rrrrrrrr](https://cloud.githubusercontent.com/assets/4592/5895023/c22850e0-a4e0-11e4-95aa-3f826a0d65ec.png)

I just took a stab at something different myself, and I'm still not excited about it:

![ehhhh](https://cloud.githubusercontent.com/assets/4592/5894994/c4d8e210-a4df-11e4-87fd-6d073faabbd9.png)

And here's another try that I don't like:

![uhhhhhh](https://cloud.githubusercontent.com/assets/4592/5895009/822a8bd4-a4e0-11e4-8f90-46f45b8909fe.png)

While our designers could probably do a far better job than me, the intrusion of "federal" always seems jarring.

Looking at our UX testing notes, there's this quote: "Could use a 1-2 sentence explanation at the top that explains what we're seeing." I think there's some merit to that, and it could be the place to disambiguate "federal". Someone besides me needs to take a shot at that, though -- and I'm curious to see how much confusion there is on the ground, since it didn't seem to be a common source of confusion in our user testing (judging solely on the notes -- @leahbannon would remember it better).

**Comment by leahbannon** [comment]
Most people with the same reaction asked for an "about" link, which I think is a better solution to the problem. I also think that clarifying "federal" but *not* specifying executive branch or that it's only participating accounts is problematic. I think we need to keep it generic. I could possibly see adding some kind of "some restrictions apply" subtext that links to about.

**Comment by konklone** [comment]
All right - I vote to close this until we see what kind of reactions we get after launch. Objectors are welcome to re-open.

**Comment by kategarklavs** [comment]
Apologies for the belated reply! My two cents: I don't think "federal" is needed directly before "government" if it appears elsewhere in close visual proximity (as in the third example). Happy to offer feedback on new designs – just let me know!
