### ISSUE TITLE
The IRS links are case sensitive

### ISSUE THREAD

**Issue by tdlowden** [GSA/analytics.usa.gov#125]
Which is why it is breaking from the dashboard.

Try it:

www.irs.gov/Forms-&-Pubs
www.irs.gov/forms-&-pubs

also happening on other irs.gov pages on the dash

http://www.irs.gov/individuals/electronic-filing-pin-request
http://www.irs.gov/Individuals/Electronic-Filing-PIN-Request

**Comment by tdlowden** [comment]
@konklone @leahbannon I think Eric mentioned you were going to hardcode these?

**Comment by tdlowden** [comment]
Whoops #69 . Apologies.

**Comment by konklone** [comment]
@tdlowden Thanks, please post them over at #69. 

We're going to hardcode fixes for any URLs that are mainstays on the top list. We're not going to hardcode anything that happens to appear on the Top listing, that will take forever and unfairly shift the burden on proper permalinkability to the DAP.

Anything we hardcode, we should send a note to the offending agency letting them know that what we're doing is a temporary solution, and that they should fix their site's permalinks so that it will continue to function on the dashboard.

**Comment by andrewhughey** [comment]
Did anyone follow up with the IRS on our case-sensitive CMS? I can point you in the right direction, but don't want to interfere if it's already in motion.

**Comment by konklone** [comment]
@andrewhughey I don't believe so, no -- by all means, put things into motion.
