### ISSUE TITLE
VISITS TODAY graph is stuck

### ISSUE THREAD

**Issue by gwynnek** [GSA/analytics.usa.gov#180]
It's now 11:53 am but the graph has not updated since the 9am data. @konklone ?

**Comment by konklone** [comment]
As I was investigating it, the problem fixed itself:

![image](https://cloud.githubusercontent.com/assets/4592/7163586/d9ece792-e368-11e4-928c-f9e7b930c643.png)

This particular chart/data has always been stubborn about keeping up to date. The data can lag behind what you see in the Google Analytics dashboard. Fundamentally, that's because we're using the non-real-time [Core Reporting API](https://developers.google.com/analytics/devguides/reporting/core/v3/reference) for what is essentially real-time data, and freshness isn't guaranteed. 

For other real-time data (like the Big Number), we use the [Real Time API](https://developers.google.com/analytics/devguides/reporting/realtime/v3/) which does provide strong guarantees of freshness.

As DAP grows, and the problem persists or gets worse (and @tdlowden has said that the 2B pageviews per month may trigger us into some different SLA threshold that could worsen this) we should probably look at revamping or replacing it with something we can populate from the Real Time API.

**Comment by konklone** [comment]
Note, I do realize the chart above shows a lower-than-expected value for 11am, it clearly reflects data from ~11:10am or something, and it's now 12:16pm. There's just not much we can do about it without reworking the data reporting. I'll open a separate issue for this.
