### ISSUE TITLE
Need to decide on link and host for dashboard

### ISSUE THREAD

**Issue by gbinal** [GSA/analytics.usa.gov#5]
* digital-analytics.usa.gov
* usa.gov/digital-analytics
* usa.gov/performance
* analytics.usa.gov 
* usa.gov/analytics 

Other ideas?

**Comment by rypan** [comment]
- usa.gov/performance
- usa.gov/analytics
- usa.gov/dashboard

i like it on usa.gov - ensures what ever is first created is designed for the public

**Comment by konklone** [comment]
I like the usa.gov domain as well. I know that usa.gov is in the early stages of a design overhaul, too.

That said, a subdomain on usa.gov would give us the flexibility to break out of the USA.gov CMS and frame. Hosting the static HTML ourselves and having the domain delegated to AWS is very simple, engineering-wise. We could manage the HTML here in GitHub Pages, and use a webhook (or something) to drive automatic deploys of the content to S3, meaning that the DAP team could use GitHub as the CMS and have the site wherever they want.

**Comment by tdlowden** [comment]
Based on the conversation we've already had with the usa.gov team and the timeline we have, I think we should stick with usa.gov. As for the subdomain or subdirectory issue, I have no preference, although I don't know the extra work it may take to get a subdomain. I echo @cew821 's comments about the word performance. We don't want to give the impression that we are assessing the quality of websites; we are merely offering a glimpse into the data. Dashboard could mean many different things, so I am most in favor of "analytics".

**Comment by cew821** [comment]
One reason I like "dashboard" is **because** it could mean a few different things... it could give us room to expand to eventually include things such as transaction data, customer satisfaction, etc.

**Comment by gbinal** [comment]
+1 to a subdomain.  I think we'd rather have 18F managing it as HTML in GitHub pages than needing to build into the USA.gov CMS and framework.  

I'm neutral between dashboard and analytics.

**Comment by konklone** [comment]
I see the value of both, but have a slight preference for analytics because it's focused and gives the user a clear expectation of what they're going to see if they click the link. (The USA's analytics.) It's very easy to set up a redirect down the line if the project expands into a proper dashboard.

I think the process wins of using a subdomain are substantial, especially the virtue of managing the content and code here in this repository. We can instrument it so that editing files here, or accepting pull requests, updates the website automatically. (Though that part doesn't have to be done for launch.)

@cew821 and I just talked offline about this, and we're both fine with "analytics.usa.gov". @tdlowden, let's talk separately and get the process started.

**Comment by gbinal** [comment]
Awesome.  This is going to be great.

**Comment by gwynnek** [comment]
The requirement was to included this in the usa.gov CMS.

**Comment by konklone** [comment]
@gwynnek Yes, that's what we arrived at on our last phone call, and I've been working with Russell and CGI throughout this week to get access to the CMS under that assumption.

Since that call, when talking through operational issues with the others helping me implement the dashboard, the benefits of using a subdomain have become more apparent. Mainly: by leaving the USA.gov CMS, we can have a cleaner design, a more flexible way of publishing, and can operate independently from the USA.gov web team.

* We can use a simpler design, that uses a lighter frame for content. As an example, Charles pointed me to https://apply.whitehouse.gov, which _feels_ like WhiteHouse.gov, but doesn't have all the extraneous components that the full WhiteHouse.gov CMS has.
* We'd get a simpler publishing model. You, @tdlowden, me, and anyone else who should have access can collaborate here and publish to the site by editing files here, rather than dealing with the USA.gov CMS authentication and deployment process. As I'm learning, that's quite tricky -- I still don't have access, and we're still working through troubleshooting to figure out why.
* Other government teammates -- and the public -- could suggest improvements, and also literally contribute features and fix bugs, and we could deploy those improvements quickly.
* If we wish to expand beyond a simple flat page, we could do that without having to rethink how we're deploying the website.

While it does imply a bit more work to replace the frame of the USA.gov CMS, our energy and resources have increased over the last several days -- Shawn Allen (@shawnbot) from 18F is helping out, and Charles Worthington (@cew821) has begun development in earnest. We're feeling very good from the perspective of being slightly more ambitious than the Crudest Possible Demo we discussed during the call. I think you'll like where it's going.

Would the DAP team be okay with changing our plan to use a subdomain (which exact one hardly matters) and putting the dashboard there? In my opinion, the additional work is small, and the return on investment is large.

**Comment by cew821** [comment]
I think right now our easiest approach would be the subdomain, because it reduces our dependencies on other things.

I think trying to get it to look correct within the CMS may wind up being one of the harder parts of the whole effort (given how far we have come working outside the CMS right now), and the fact that Eric hasn't gotten access to the CMS after working diligently with the contractors since Monday days does not give me confidence. 

My thinking right now is that we should aim towards the simplest approach (hosting it ourselves) and then further evaluate moving it to the CMS once we know what we want.

**Comment by gwynnek** [comment]
From a business owner POV, I am attracted to the usa.gov CMS especially in that it is currently supported infrastructure in our group and that after your team moves on, I will be able to keep the lights on. While I totally get how easy it is for you all to work within github for updates, for us we are more WordPress and template kinda folks rather than Markdown.

Understanding the design challenge that a template provides, there are many roads to Damascus. The goal here is to present the information to the public. The gov.uk model of stacking the graphs is a decent way to present the information.
