### ISSUE TITLE
Show/hide all OS and browser version breakdown onclick

### ISSUE THREAD

**Issue by leahbannon** [GSA/analytics.usa.gov#55]

**Comment by CpuID** [comment]
Being able to see browser + OS combinations would be awesome :) eg, Safari on OSX vs Safari on iOS, Chrome on Windows vs OSX, etc. Obviously versions below that also :)

**Comment by konklone** [comment]
> Being able to see browser + OS combinations would be awesome :) eg, Safari on OSX vs Safari on iOS, Chrome on Windows vs OSX, etc. Obviously versions below that also :)

That would be pretty great. It seems like the sort of thing that would be easier as a data-only release, rather than coming up with complicated UX.

This ticket was originally for something else though, and something I think we've moved on from. So I'm going to close this particular issue thread, but this is good feedback and I appreciate it!
