### ISSUE TITLE
some of the links in the Top 20 don't work :(

### ISSUE THREAD

**Issue by leahbannon** [GSA/analytics.usa.gov#69]
halp

**Comment by konklone** [comment]
Here are some examples:

* https://applicationmanager.gov/Login.aspx
* https://egov.uscis.gov/casestatus/mycasestatus.do
* http://forecast.weather.gov/mapclick.php
* http://ebenefits.va.gov/ebenefits-portal/ebenefits.portal
* http://www.irs.gov/individuals/electronic-filing-pin-request
* http://www.irs.gov/individuals/get-transcript
* http://www.irs.gov/payments/direct-pay

I'm not sure what's up with the mapclick one, but the rest are all services that don't use permalinks. Users arrive at them by filling out forms, but the system isn't prepared for people to go right to the URL. 

It's enough of them that this is definitely going to raise questions. However, I'm not at all sure what to do about them, besides building a hardcoded list of exceptions (with alternative URLs) or something. That'd be easy to do for launch, but a hellish thing to maintain over time. The list is so useful otherwise that my inclination is essentially to leave it, and put pressure on agencies to make sure those links go somewhere useful when clicked on -- but that may be a big lift for these services in the short term, which are (clearly) high-traffic important production systems.

halp

**Comment by leahbannon** [comment]
This sounds like a issue for @gbinal to weigh in on.

**Comment by gbinal** [comment]
I think we don't do anything to address it.  Yes, it's ugly but it's better that that ugliness get out there and be known.  

We'll have all kinds of outreach and education to do as a result of this and, like @konklone says, should engage on this front, too.

**Comment by leahbannon** [comment]
Now:
- [ ] http://applicationmanager.gov/application.aspx -> either https://applicationmanager.gov or https://www.usajobs.gov
- [ ] http://forecast.weather.gov/mapclick.php -> http://forecast.weather.gov
- [ ] https://egov.uscis.gov/casestatus/mycasestatus.do -> https://egov.uscis.gov/casestatus/
- [ ] http://irs.gov/individuals/electronic-filing-pin-request -> http://www.irs.gov/Individuals/Electronic-Filing-PIN-Request
- [ ] http://ebenefits.va.gov/ebenefits-portal/ebenefits.portal -> https://www.ebenefits.va.gov/ebenefits-portal/ebenefits.portal

7 Days:
- [ ] egov.uscis.gov -> https://egov.uscis.gov/casestatus/
- [ ] wrh.noaa.gov -> http://www.wrh.noaa.gov/

30 Days: 
- [ ]
