### ISSUE TITLE
7 and 30 days data not quite congruent

### ISSUE THREAD

**Issue by tdlowden** [GSA/analytics.usa.gov#85]
I ran reports in DAP for the sessions over 7 and 30 days. They are *close*, but not the same in the dashboard, and it sometimes affects the ranking of sites even if they are off by a little bit. I imagine this has to do with the API sampling thresholds. See shots below.

30-day
![screen shot 2015-01-16 at 8 36 02 am](https://cloud.githubusercontent.com/assets/6556888/5776859/293bfd0a-9d5b-11e4-9590-279c0e5aff1d.png)
![screen shot 2015-01-16 at 8 35 28 am](https://cloud.githubusercontent.com/assets/6556888/5776858/29370c28-9d5b-11e4-9427-1a1efdfd471a.png)

7 day
![screen shot 2015-01-16 at 8 37 10 am](https://cloud.githubusercontent.com/assets/6556888/5776865/329d4336-9d5b-11e4-82c9-83a75db13145.png)
![screen shot 2015-01-16 at 8 36 54 am](https://cloud.githubusercontent.com/assets/6556888/5776866/32a362b6-9d5b-11e4-836f-d7dbfebef8f4.png)

**Comment by tdlowden** [comment]
In the 30 day, nps is off by a half million, which affects its relative position a fair amount. In the 7 day, for example, usajobs and weather.gov switched positions. I'm not sure how much this *really* matters, but we should definitely include verbiage saying "approximate" or "estimated" if we can't fix it. @konklone @leahbannon

**Comment by tdlowden** [comment]
FYI, the DAP reports encompass 100% of sessions, so they should be the most accurate thing we have.

**Comment by konklone** [comment]
I can verify that our reports are currently receiving non-sampled data. All of them get reports back from Google with `"containsSampledData": false,` and according to [the docs](https://developers.google.com/analytics/devguides/reporting/core/v3/reference#sampling) that means they're complete.

@tdlowden I just did about an hour or so of research on this. I was not able to reproduce a difference between the GA console and the data for the "Last 7 days" report. I was able to confirm a difference in GA's month view and the "Last 30 days" report -- but I think that's because January has 31 days, and Google tries to be smart and show the last "month". When I set the time range to be the last "30 days", I get matched up data:

![30 days](https://cloud.githubusercontent.com/assets/4592/5796499/0b994c80-9f77-11e4-9d1a-0744f02d9b78.png)

![30 days 2](https://cloud.githubusercontent.com/assets/4592/5796502/1ab21544-9f77-11e4-8d40-d8c349c2e065.png)

I'd like to compare notes with you during the middle of the business day/week, but I'm considering this, for now, closed.
